### ISSUE TITLE
parseDescriptors panics

### ISSUE THREAD

**Issue by vladimir-ch** [asticode/go-astits#2]
I have a test file that produces a panic in `parseDescriptors` from current master:
```
$ astits -i test.ts -v
DEBU[0000] Fetching data...
DEBU[0000] astits: unlisted descriptor tag 0x6
DEBU[0000] astits: unlisted descriptor tag 0xf
DEBU[0000] astits: unlisted descriptor tag 0xfe
DEBU[0000] astits: unlisted descriptor tag 0xf
DEBU[0000] astits: unlisted descriptor tag 0xfe
DEBU[0000] astits: unlisted descriptor tag 0xf
DEBU[0000] astits: unlisted descriptor tag 0xfe
DEBU[0000] astits: unlisted descriptor tag 0xf
DEBU[0000] astits: unlisted descriptor tag 0x90
DEBU[0000] astits: unlisted descriptor tag 0xfe
DEBU[0000] astits: unlisted descriptor tag 0xf
...
DEBU[0000] astits: unlisted descriptor tag 0xfe         
DEBU[0000] astits: unlisted descriptor tag 0xf          
DEBU[0000] astits: unlisted descriptor tag 0xfe         
DEBU[0000] astits: unlisted descriptor tag 0xf          
DEBU[0000] astits: unlisted descriptor tag 0x90         
DEBU[0000] astits: unlisted descriptor tag 0xfe         
DEBU[0000] astits: unlisted descriptor tag 0xf          
DEBU[0000] astits: unlisted descriptor tag 0x90         
DEBU[0000] astits: unlisted descriptor tag 0xfe         
DEBU[0000] astits: unlisted descriptor tag 0xf
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/asticode/go-astits.parseDescriptors(0xc420420240, 0xb8, 0xb8, 0xc4200538b8, 0x5, 0xc42029d940, 0x4)
	/home/chalupecky/src/github.com/asticode/go-astits/descriptor.go:791 +0x10b2
github.com/asticode/go-astits.parsePMTSection(0xc420420240, 0xb8, 0xb8, 0xc4200538b8, 0x11e, 0x411b1c, 0x10)
	/home/chalupecky/src/github.com/asticode/go-astits/data_pmt.go:51 +0x1a2
github.com/asticode/go-astits.parsePSISectionSyntaxData(0xc420420240, 0xb8, 0xb8, 0xc4200538b8, 0xc4200c7780, 0xc4201893e0, 0x11e, 0x1)
	/home/chalupecky/src/github.com/asticode/go-astits/data_psi.go:318 +0x57c
github.com/asticode/go-astits.parsePSISectionSyntax(0xc420420240, 0xb8, 0xb8, 0xc4200538b8, 0xc4200c7780, 0x11e, 0x4)
	/home/chalupecky/src/github.com/asticode/go-astits/data_psi.go:261 +0xc2
github.com/asticode/go-astits.parsePSISection(0xc420420240, 0xb8, 0xb8, 0xc4200538b8, 0x524477, 0xc4200bc008, 0xc4200b8030, 0xc4200538c6)
	/home/chalupecky/src/github.com/asticode/go-astits/data_psi.go:120 +0x174
github.com/asticode/go-astits.parsePSIData(0xc420420240, 0xb8, 0xb8, 0xc420420201, 0xb8, 0xb8)
	/home/chalupecky/src/github.com/asticode/go-astits/data_psi.go:93 +0x104
github.com/asticode/go-astits.parseData(0xc42000e1f0, 0x1, 0x1, 0x0, 0xc4200bc008, 0xc4200b8030, 0x0, 0x409130, 0xc4201893c2, 0xea3e6e4c, ...)
	/home/chalupecky/src/github.com/asticode/go-astits/data.go:58 +0x453
github.com/asticode/go-astits.(*Demuxer).NextData(0xc4200be000, 0xc420053c60, 0xc4201893c2, 0xc420053cf0)
	/home/chalupecky/src/github.com/asticode/go-astits/demuxer.go:128 +0x156
main.programs(0xc4200be000, 0xc420010200, 0x673b20, 0xc4200b4000, 0x0, 0x0)
	/home/chalupecky/src/github.com/asticode/go-astits/astits/main.go:238 +0x31f
main.main()
	/home/chalupecky/src/github.com/asticode/go-astits/astits/main.go:79 +0x2dc
```

**Comment by asticode** [comment]
@vladimir-ch very interesting. Is there any way I could have access to that input file or is this something you don't want to do?

**Comment by asticode** [comment]
@vladimir-ch I've fixed the panic and I've also added the descriptors 0x6 and 0xf (not in the printed result though).

Does this fix your issue?

**Comment by vladimir-ch** [comment]
Yes, it does. Thanks!

**Comment by asticode** [comment]
Cheers
