### ISSUE TITLE
panic: runtime error: index out of range in parseEITSection

### ISSUE THREAD

**Issue by gy741** [asticode/go-astits#3]
Hello.

I found a index out of range bug in go-astits.

Please confirm.

Thanks.

reproduce code:

```
package astits

import (
	"testing"
)



func Test(t *testing.T) {
	var offset int
	inputs := []string{
			"7",
	}
	for _, input := range inputs {
		parseEITSection([]byte(input), &offset, len(input), uint16(1))
	}
}
```

Crash Log

```
--- FAIL: Test (0.00s)
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 34 [running]:
panic(0x67bd00, 0xc42000c140)
	/usr/lib/go-1.7/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc42017f380)
	/usr/lib/go-1.7/src/testing/testing.go:579 +0x25d
panic(0x67bd00, 0xc42000c140)
	/usr/lib/go-1.7/src/runtime/panic.go:458 +0x243
github.com/asticode/go-astits.parseEITSection(0xc42025cfa0, 0x1, 0x8, 0xc420025f48, 0x1, 0x1, 0x45e4e3)
	/home/karas/go/src/github.com/asticode/go-astits/data_eit.go:32 +0x48f
github.com/asticode/go-astits.Test(0xc42017f380)
	/home/karas/go/src/github.com/asticode/go-astits/fuzz_test.go:15 +0xb1
testing.tRunner(0xc42017f380, 0x6edf18)
	/usr/lib/go-1.7/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
	/usr/lib/go-1.7/src/testing/testing.go:646 +0x2ec
exit status 2
FAIL	github.com/asticode/go-astits	0.009s
```

**Comment by asticode** [comment]
@gy741 this is "normal". I'm not checking the length of bytes on purpose because at the stage of this project, I'd rather have it panic if anything goes wrong.

In your test, the input you're feeding the function is invalid hence the panic.

For now, I'd rather leave it that way but I'll add a note in the readme.
